#!/usr/bin/env bash
# Regenerate every headline number this project asserts, in one command.
#
# P7.2's gate is "every number in it regenerable by one command", and P7.1 names the same thing as
# its prerequisite: a total across the rule x initial-state matrix, because no per-configuration
# measurement substitutes for it. This is that command.
#
# WHAT IT IS NOT. It does not assert. The gates assert -- all_tests, gpu_differential_tests,
# codemap_check each fail on their own. This REPORTS, so a number in a document can be checked
# against a number regenerated today, and a claim that has quietly stopped being true becomes
# visible rather than staying written down.
#
# WALL CLOCK IS NOT USED ANYWHERE HERE. It drifts more than 10% run to run on this hardware,
# which is larger than most effects worth attributing. Where a cost is reported it is callgrind
# instructions or arena/heap bytes, both deterministic. MEASURED, on two consecutive runs of this
# script: the corpus total moved 3,125,670,179 -> 3,125,675,709 and the Full/IR route 59,028,301
# -> 59,028,419, both about 2 parts per million. That is the reproducibility a number quoted in a
# document needs, and it is four orders of magnitude tighter than the clock.
#
# A LEG THAT CANNOT RUN SAYS SO. No GPU, no wolframscript, no valgrind: each is reported as
# SKIPPED with the reason. Silently omitting a leg would let the report read as complete evidence
# for a machine that produced only part of it.
#
# Usage: tools/dev/evidence.sh [output.md]
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="${1:-$ROOT/evidence/REPORT.md}"
mkdir -p "$(dirname "$OUT")"
cd "$ROOT"

BUILD=build_linux
GPU_BUILD=build_gpu
export PATH="$PATH:/usr/lib/wsl/lib"

say() { printf '%s\n' "$*" >>"$OUT"; }
run_or_skip() {   # run_or_skip <label> <guard-command> <command...>
    local label="$1"; shift
    local guard="$1"; shift
    if ! eval "$guard" >/dev/null 2>&1; then
        say "- **$label** — SKIPPED: \`$guard\` did not hold on this machine."
        return
    fi
    say ""
    say "### $label"
    say ""
    say '```'
    "$@" 2>&1 | tail -40 >>"$OUT"
    say '```'
}

: >"$OUT"
say "# Evidence report"
say ""
say "Regenerated by \`tools/dev/evidence.sh\`. Every number below is produced by the command"
say "shown with it; nothing here is transcribed from a document."
say ""
say "- commit: \`$(git rev-parse --short HEAD)\` on \`$(git rev-parse --abbrev-ref HEAD)\`"
say "- host: \`$(uname -srm)\`, $(nproc) cores"
say "- generated: $(date -u '+%Y-%m-%d %H:%M UTC')"
say ""
say "Wall clock appears nowhere. Costs are callgrind instructions or arena/heap bytes."
say ""

say "## Correctness"
run_or_skip "Oracle corpus, static analysis, record set, serial, continuation" \
    "test -x $BUILD/all_tests" \
    "$BUILD/all_tests" --gtest_filter='OracleCorpus.*:Unified_CanonicalHash.*:GoldenMatrix.*'

run_or_skip "Match completeness: late arrivals separated from real losses" \
    "test -x $BUILD/all_tests" \
    "$BUILD/all_tests" --gtest_filter='MatchCompleteness.*'

run_or_skip "Quotient reconstruction vs full capture, 80 configurations" \
    "test -x $BUILD/quotient_reconstruction_observables_probe" \
    "$BUILD/quotient_reconstruction_observables_probe"

run_or_skip "Quotient causal determinism rate, under load" \
    "test -x $BUILD/quotient_determinism_rate_probe" \
    "$BUILD/quotient_determinism_rate_probe" 25 --load 4

say ""
say "## Cost, on the deterministic axes"
run_or_skip "Cost matrix: arena and heap per workload, with and without the relations" \
    "test -x $BUILD/cost_matrix" \
    "$BUILD/cost_matrix"

# P7.1 names this its prerequisite: "an end-to-end corpus timing harness reporting TOTAL time
# across the full rule x initial-state matrix, since that is the number to drive down and no
# per-configuration measurement substitutes for it". Instructions rather than time, because time
# is not measurable here to better than 10%. A fixed depth of 3 keeps every workload in the matrix
# comparable and the whole sweep at about 11 seconds under callgrind.
run_or_skip "END-TO-END TOTAL: instructions for the entire corpus at a fixed depth" \
    "command -v valgrind && test -x $BUILD/cost_matrix" \
    bash -c "valgrind --tool=callgrind --callgrind-out-file=/dev/null $BUILD/cost_matrix 3 2>&1 |
             grep -E 'I *refs:'"

run_or_skip "Canonicalization route: instructions for the whole evolution, Full/IR vs None/WL" \
    "command -v valgrind && test -x $BUILD/profile_evolve" \
    bash -c "
      for m in full none; do
        printf '%-6s ' \"\$m\"
        valgrind --tool=callgrind --callgrind-out-file=/dev/null \
                 $BUILD/profile_evolve 5 \$m 1 2>&1 |
          grep -oE 'refs: *[0-9,]+' | tail -1
      done"

say ""
say "## Structure and documentation"
run_or_skip "CODEMAP names what exists, and names everything that exists" \
    "test -f tools/dev/codemap_check.py" \
    python3 tools/dev/codemap_check.py

run_or_skip "Option surface: declared == sent == parsed == documented" \
    "test -x $BUILD/all_tests" \
    "$BUILD/all_tests" --gtest_filter='OptionSurface.*'

say ""
say "## Device"
run_or_skip "CPU/GPU differential" \
    "test -x $GPU_BUILD/gpu_differential_tests && nvidia-smi" \
    "$GPU_BUILD/gpu_differential_tests"

run_or_skip "Device unit suite" \
    "test -x $GPU_BUILD/hg_gpu_tests && nvidia-smi" \
    "$GPU_BUILD/hg_gpu_tests"

say ""
say "---"
say ""
say "Legs reported SKIPPED above did not run on this machine. A report with skips is evidence"
say "for what it ran and for nothing else."
echo "wrote $OUT"
