#!/usr/bin/env python3
"""Generate the paper's measurement tables from the instruments that produce them.

Each table is written to paper/tables/<name>.tex and \\input by paper/main.tex, so a
number in the paper is a file the tools wrote and not a value someone typed. Every
table carries the commit, the machine and the tool it came from; regenerating on a
different machine rewrites those lines with it.

Run:  python3 tools/dev/paper_tables.py [--gpu] [--build-dir build_linux]

--gpu adds the device tables, which need a CUDA build and a visible GPU.
"""

import argparse
import os
import platform
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "paper", "tables")


def run(cmd, timeout=1800):
    p = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, timeout=timeout)
    if p.returncode != 0:
        raise SystemExit("FAILED (%d): %s\n%s" % (p.returncode, " ".join(cmd), p.stderr[-2000:]))
    return p.stdout


def commit():
    return run(["git", "rev-parse", "--short", "HEAD"]).strip()


def machine():
    cpu = "unknown"
    try:
        with open("/proc/cpuinfo") as f:
            for line in f:
                if line.startswith("model name"):
                    cpu = line.split(":", 1)[1].strip()
                    break
    except OSError:
        pass
    mem_gb = "?"
    try:
        with open("/proc/meminfo") as f:
            kb = int(f.readline().split()[1])
            mem_gb = "%.0f" % (kb / 1048576.0)
    except (OSError, ValueError, IndexError):
        pass
    return "%s, %s GB RAM, %s %s" % (cpu, mem_gb, platform.system(), platform.release())


def provenance(tool):
    return ("%% GENERATED by tools/dev/paper_tables.py -- do not edit.\n"
            "%% commit %s | %s | source: %s\n" % (commit(), machine(), tool))


def tex_escape(s):
    return s.replace("_", r"\_").replace("&", r"\&").replace("%", r"\%")


def write(name, body):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, name)
    with open(path, "w") as f:
        f.write(body)
    print("wrote %s" % os.path.relpath(path, ROOT))


# --- T1: exactness and deterministic memory, one row per corpus workload ------------

def t1(build):
    out = run([os.path.join(build, "cost_matrix")])
    rows = []
    total = ""
    for line in out.splitlines():
        m = re.match(r"^(\S+)\s+(\S+)\s+(EXACT|INEXACT|\S+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+"
                     r"(\d+)\s+(\d+)\s+(\d+)\s+(\d+)", line)
        if m:
            rows.append(m.groups())
        elif line.startswith("arena bytes, all artifacts"):
            total = line.strip()
    if not rows:
        raise SystemExit("cost_matrix produced no parseable rows")

    b = [provenance("tools/cost_matrix.cpp"),
         r"\begin{tabular}{llrrrrrrrl}", r"\toprule",
         r"Workload & Class & Canon.\ states & Events & Causal & Branchial & "
         r"Arena B & Heap B & Heap allocs & Exactness \\", r"\midrule"]
    for (case, cls, exact, canon, ev, ca, br, arena, heapb, heapa, _norel) in rows:
        b.append("%s & %s & %s & %s & %s & %s & %s & %s & %s & \\textsc{%s} \\\\" % (
            tex_escape(case), tex_escape(cls), canon, ev, ca, br, arena, heapb, heapa,
            exact.lower()))
    b += [r"\bottomrule", r"\end{tabular}", "", "%% " + total]
    write("t1_exactness.tex", "\n".join(b) + "\n")
    return len(rows)


# --- T8: thread scaling, and the single-thread column T2 compares against -----------

def scaling(build, tool, name, steps, iters, caption_tool):
    out = run([os.path.join(build, tool), str(steps), str(iters)], timeout=3600)
    rows = []
    for line in out.splitlines():
        m = re.search(r"threads=(\d+)\s+steps=(\d+)\s+canonical=(\d+)\s+raw=(\d+)\s+"
                      r"median_ms=([\d.]+)\s+min_ms=([\d.]+)", line)
        if m:
            rows.append(m.groups())
    if not rows:
        raise SystemExit("%s produced no parseable rows:\n%s" % (tool, out[-2000:]))
    base = float(rows[0][4])
    b = [provenance(caption_tool),
         r"\begin{tabular}{rrrrrr}", r"\toprule",
         r"Threads & Steps & Canonical states & Raw states & Median ms & Speedup vs.\ 1 thread \\",
         r"\midrule"]
    for (th, st, canon, raw, med, _mn) in rows:
        b.append("%s & %s & %s & %s & %s & %.2f \\\\" % (th, st, canon, raw, med, base / float(med)))
    b += [r"\bottomrule", r"\end{tabular}"]
    write(name, "\n".join(b) + "\n")
    return len(rows)


def t7(build, gpu_build, steps_list, iters):
    """GPU against CPU on ONE workload, at increasing depth.

    bench_cpu_evolve and bench_gpu_evolve run the same WPP rule, the same two-edge initial
    condition, Full canonicalization and quotient exploration, so the medians are comparable.
    Both are medians of the same iteration count taken in the same session, because wall clock
    on this class of machine drifts more between sessions than the effects being reported.
    """
    rows = []
    for st in steps_list:
        gout = run([os.path.join(gpu_build, "bench_gpu_evolve"), str(st), str(iters)], timeout=3600)
        m = re.search(r"steps=(\d+) states=(\d+) events=(\d+) \| evolve\(\)_median_ms=([\d.]+) \| "
                      r"PersistentEvolver_median_ms=([\d.]+)", gout)
        if not m:
            raise SystemExit("bench_gpu_evolve produced no parseable row:\n%s" % gout[-2000:])
        _, states, events, gpu_call, gpu_persist = m.groups()

        cout = run([os.path.join(build, "bench_cpu_evolve"), str(st), str(iters)], timeout=3600)
        cpu = {}
        for line in cout.splitlines():
            c = re.search(r"threads=(\d+)\s+steps=\d+\s+canonical=\d+\s+raw=(\d+)\s+median_ms=([\d.]+)", line)
            if c:
                cpu[int(c.group(1))] = float(c.group(3))
        if 1 not in cpu or 8 not in cpu:
            raise SystemExit("bench_cpu_evolve gave no 1- and 8-thread rows:\n%s" % cout[-2000:])
        rows.append((st, states, events, cpu[1], cpu[8], float(gpu_persist), float(gpu_call)))

    b = [provenance("tools/bench_cpu_evolve.cpp + tools/bench_gpu_evolve.cpp"),
         r"\begin{tabular}{rrrrrrrr}", r"\toprule",
         r"Steps & Raw states & Events & CPU 1t ms & CPU 8t ms & GPU ms & vs.\ CPU 1t & vs.\ CPU 8t \\",
         r"\midrule"]
    for (st, states, events, c1, c8, gpu, _call) in rows:
        b.append("%d & %s & %s & %.1f & %.1f & %.1f & %.2f & %.2f \\\\" % (
            st, states, events, c1, c8, gpu, c1 / gpu, c8 / gpu))
    b += [r"\bottomrule", r"\end{tabular}"]
    write("t7_gpu.tex", "\n".join(b) + "\n")
    return len(rows)


def t6(build, maxd):
    """Quotient exploration against full capture, and what exactness costs on top.

    One workload (wolfram-2to4) at increasing depth. The events and causal columns are the
    point: quotient alone reports fewer, quotient plus reconstruction reports the full-capture
    numbers exactly, at the quotient's cost.
    """
    out = run([os.path.join(build, "quotient_reconstruction_cost_probe"), str(maxd)], timeout=3600)
    rows = []
    for line in out.splitlines():
        m = re.match(r"\s*(\d+) \|\s*(\d+)\s+(\d+)\s+(\d+)\s+([\d.]+) \|"
                     r"\s*(\d+)\s+(\d+)\s+(\d+)\s+([\d.]+) \|"
                     r"\s*(\d+)\s+(\d+)\s+(\d+)\s+([\d.]+)\s+(\w+)", line)
        if m:
            rows.append(m.groups())
    if not rows:
        raise SystemExit("quotient probe produced no parseable rows:\n%s" % out[-2000:])
    b = [provenance("tools/quotient_reconstruction_cost_probe.cpp"),
         r"\begin{tabular}{rrrrrrrrl}", r"\toprule",
         r"Depth & Events (full) & Causal (full) & ms (full) & Events (quot.) & ms (quot.) & "
         r"Events (quot.+recon) & ms (quot.+recon) & Exact \\", r"\midrule"]
    for (d, _fst, fev, fca, fms, _qst, qev, _qca, qms, _rst, rev, _rca, rms, exact) in rows:
        b.append("%s & %s & %s & %s & %s & %s & %s & %s & \\textsc{%s} \\\\" % (
            d, fev, fca, fms, qev, qms, rev, rms, exact))
    b += [r"\bottomrule", r"\end{tabular}"]
    write("t6_quotient.tex", "\n".join(b) + "\n")
    return len(rows)


def wolframscript():
    """The kernel driver, native if present, else the Windows install this box runs under WSL."""
    from shutil import which
    exe = os.environ.get("HG_WOLFRAMSCRIPT") or which("wolframscript")
    if exe:
        return [exe], False
    import glob
    cands = sorted(glob.glob("/mnt/c/Program Files/Wolfram*/*/*/wolframscript.exe"))
    if cands:
        return [cands[-1]], True
    return None, False


def t2(build, maxd, reps):
    """The engine against the authority, on one workload, at increasing depth.

    Wolfram/Multicomputation's MultiwaySystem is the oracle the engine is validated against, so
    it is also the reference a wall time means something against. The state count is carried in
    the table because a timing comparison between two different state spaces is not one; the
    event and causal counts are NOT compared here, because the two sides' event-identity
    conventions are their own question and are gated separately.
    """
    ws, windows = wolframscript()
    if not ws:
        print("T2 skipped: no wolframscript on this machine")
        return 0
    script = os.path.join(ROOT, "reference", "bench_authority.wls")
    if windows:
        script = subprocess.run(["wslpath", "-w", script], capture_output=True, text=True).stdout.strip()
    out = run(ws + ["-file", script, str(maxd), str(reps)], timeout=3600)
    auth = {}
    for line in out.splitlines():
        m = re.search(r"AUTH d=(\d+) states=(\d+) causal=(\d+) ms=([\d.]+)", line)
        if m:
            auth[int(m.group(1))] = (int(m.group(2)), float(m.group(4)))
    if "AUTH_DONE" not in out:
        print("T2: the kernel did not finish; using the %d depths it printed" % len(auth))
    if not auth:
        raise SystemExit("bench_authority.wls printed no rows:\n%s" % out[-2000:])

    eng = run([os.path.join(build, "quotient_reconstruction_cost_probe"), str(max(auth))],
              timeout=3600)
    engine = {}
    for line in eng.splitlines():
        m = re.match(r"\s*(\d+) \|\s*(\d+)\s+\d+\s+\d+\s+([\d.]+) \|", line)
        if m:
            engine[int(m.group(1))] = (int(m.group(2)), float(m.group(3)))

    b = [provenance("reference/bench_authority.wls + tools/quotient_reconstruction_cost_probe.cpp"),
         r"\begin{tabular}{rrrrrl}", r"\toprule",
         r"Depth & States & Authority ms & Engine ms & Speedup & States agree \\", r"\midrule"]
    for d in sorted(auth):
        a_states, a_ms = auth[d]
        if d not in engine:
            continue
        e_states, e_ms = engine[d]
        agree = "yes" if a_states == e_states else "NO (%d vs %d)" % (a_states, e_states)
        b.append("%d & %d & %.1f & %.1f & %.0f$\\times$ & %s \\\\" % (
            d, a_states, a_ms, e_ms, a_ms / e_ms, agree))
    b += [r"\bottomrule", r"\end{tabular}"]
    write("t2_speedup.tex", "\n".join(b) + "\n")
    return len(auth)


def t9(build, iters):
    """Per-contribution ablation, from the switches the shipped binary still has.

    There are no compiled-out ablation builds to run: when a replacement lands here the
    replaced path is deleted in the same commit, so an "off" arm exists only where the choice
    is still a live switch. Those are match forwarding (which the rule set decides) and the
    state-canonicalization mode. Each row is a median over the same iteration count, and the
    state and event counts are printed so a row that changed the ANSWER is visible rather than
    read as a speedup.
    """
    def smoke(arm, rule, edges, steps, canon):
        best = None
        for _ in range(max(3, iters // 3)):
            out = run([os.path.join(build, "sampling_cost_smoke"), arm, rule, str(edges),
                       str(steps), "4", "4", canon], timeout=1800)
            m = re.search(r"done ([\d.]+) ms\s+states=(\d+).*events=(\d+)", out)
            if not m:
                raise SystemExit("sampling_cost_smoke gave no row:\n%s" % out[-1000:])
            ms, st, ev = float(m.group(1)), m.group(2), m.group(3)
            if best is None or ms < best[0]:
                best = (ms, st, ev)
        return best

    rows = []
    a = smoke("off", "growth", 1, 8, "full")       # forwarding decided: off on a one-edge LHS
    b = smoke("fwdon", "growth", 1, 8, "full")     # forced on
    rows.append(("Match forwarding, one-edge LHS", "on", b, "decided off", a))
    a = smoke("off", "pair", 4, 6, "full")         # forwarding decided: on for a two-edge LHS
    b = smoke("fwdoff", "pair", 4, 6, "full")      # forced off
    rows.append(("Match forwarding, two-edge LHS", "off", b, "decided on", a))
    a = smoke("off", "pair", 4, 6, "automatic")
    b = smoke("off", "pair", 4, 6, "full")
    rows.append(("State canonicalization", "Full (exact)", b, "Automatic (hash)", a))

    b_ = [provenance("tools/sampling_cost_smoke.cpp"),
          r"\begin{tabular}{lllrlrl}", r"\toprule",
          r"Contribution & Arm A & A ms & Arm B & B ms & Ratio & Same answer \\", r"\midrule"]
    for (name, an, av, bn, bv) in rows:
        same = "yes" if (av[1], av[2]) == (bv[1], bv[2]) else "NO"
        b_.append("%s & %s & %.1f & %s & %.1f & %.2f & %s \\\\" % (
            name, an, av[0], bn, bv[0], av[0] / bv[0], same))
    b_ += [r"\bottomrule", r"\end{tabular}"]
    write("t9_ablation.tex", "\n".join(b_) + "\n")
    return len(rows)


def t3(build):
    """Is the global allocator on the concurrent path?

    The de-heap, the causal-closure rework and the copy-on-write states were scaffolded in the
    paper as three before/after tables. Their "before" columns are not reproducible as a
    comparison: each replaced path was deleted in the commit that replaced it (there is no build
    flag that restores it), the work spans dozens of commits on one branch, and the instrument
    that measures arena bytes today did not exist at the far end -- so a before/after pair would
    be two different instruments reporting one column.

    What IS checkable, and is the claim those three items were for: allocation count does not
    grow with the work. cost_matrix counts every global operator new during the measured
    evolution, so the table below puts that count next to the size of the run it served.
    """
    out = run([os.path.join(build, "cost_matrix")])
    rows = []
    for line in out.splitlines():
        m = re.match(r"^(\S+)\s+(\S+)\s+(EXACT|INEXACT|\S+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+"
                     r"(\d+)\s+(\d+)\s+(\d+)\s+(\d+)", line)
        if m:
            g = m.groups()
            rows.append((g[0], int(g[3]), int(g[4]), int(g[7]), int(g[9])))
    if not rows:
        raise SystemExit("cost_matrix produced no parseable rows")
    rows.sort(key=lambda r: r[2])   # by events: the work, which is what allocation must not track

    b = [provenance("tools/cost_matrix.cpp"),
         r"\begin{tabular}{lrrrrr}", r"\toprule",
         r"Workload & Canon.\ states & Events & Arena B & Heap allocs & Allocs per event \\",
         r"\midrule"]
    for (name, canon, ev, arena, allocs) in rows:
        per = ("%.4f" % (float(allocs) / ev)) if ev else "--"
        b.append("%s & %d & %d & %d & %d & %s \\\\" % (
            tex_escape(name), canon, ev, arena, allocs, per))
    b += [r"\bottomrule", r"\end{tabular}"]
    write("t3_heap.tex", "\n".join(b) + "\n")
    return len(rows)


def t10(build):
    """What each event-identity convention identifies, on the same runs.

    The three conventions are refinements of one another: ByEndpointStates calls two rewrites the
    same event when they run between the same states, ByConsumedProducedEdges when they also move
    the same edges, DistinctApplications never. Reading the CANONICAL EVENT COUNT across them on
    a fixed workload is what shows they are distinct points rather than one convention wearing
    three names -- which inspection cannot show, because a duplicated convention still equals
    itself.

    The counts are taken under Full state canonicalization, one thread. No timing column: the
    conventions differ in what they IDENTIFY, and the cost of the identity is the added IR pass,
    which T9's canonicalization row already measures.
    """
    out = run([os.path.join(build, "mode_matrix_probe")], timeout=1800)
    rows = []
    workload = None
    for line in out.splitlines():
        m = re.match(r"^(\S+) \(steps=(\d+)\)", line)
        if m:
            workload, steps = m.group(1), m.group(2)
            continue
        m = re.match(r"^\s+Full\s+(\d+)/(\d+)/(\d+)/(\d+)\s+(\d+)/(\d+)/(\d+)/(\d+)\s+(\d+)/(\d+)/(\d+)/(\d+)", line)
        if m and workload:
            g = [int(x) for x in m.groups()]
            rows.append((workload, steps, g[0], g[1], g[5], g[9]))
            workload = None
    if not rows:
        raise SystemExit("mode_matrix_probe produced no parseable Full rows:\n%s" % out[-2000:])

    b = [provenance("tools/mode_matrix_probe.cpp"),
         r"\begin{tabular}{lrrrrr}", r"\toprule",
         r"Workload & Steps & Canon.\ states & By endpoint states & By consumed/produced edges & "
         r"Distinct applications \\", r"\midrule"]
    for (name, steps, canon, e1, e2, e3) in rows:
        b.append("%s & %s & %d & %d & %d & %d \\\\" % (tex_escape(name), steps, canon, e1, e2, e3))
    b += [r"\bottomrule", r"\end{tabular}"]
    write("t10_event_canon.tex", "\n".join(b) + "\n")
    return len(rows)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--build-dir", default="build_linux")
    ap.add_argument("--gpu-build-dir", default="build_gpu")
    ap.add_argument("--gpu", action="store_true")
    ap.add_argument("--steps", type=int, default=6)
    ap.add_argument("--iters", type=int, default=15)
    ap.add_argument("--quotient-depth", type=int, default=7)
    ap.add_argument("--authority-depth", type=int, default=5)
    ap.add_argument("--reps", type=int, default=3)
    ap.add_argument("--wolfram", action="store_true",
                    help="add T2, which needs a Wolfram kernel")
    a = ap.parse_args()

    n = t1(a.build_dir)
    print("T1: %d workloads" % n)
    n = scaling(a.build_dir, "bench_cpu_evolve", "t8_scaling.tex", a.steps, a.iters,
                "tools/bench_cpu_evolve.cpp")
    print("T8: %d thread counts" % n)
    if a.wolfram:
        n = t2(a.build_dir, a.authority_depth, a.reps)
        print("T2: %d depths" % n)
    n = t10(a.build_dir)
    print("T10: %d workloads" % n)
    n = t3(a.build_dir)
    print("T3: %d workloads" % n)
    n = t9(a.build_dir, a.iters)
    print("T9: %d contributions" % n)
    n = t6(a.build_dir, a.quotient_depth)
    print("T6: %d depths" % n)
    if a.gpu:
        n = t7(a.build_dir, a.gpu_build_dir, [5, 6, 7], a.iters)
        print("T7: %d depths" % n)
    return 0


if __name__ == "__main__":
    sys.exit(main())
