#!/usr/bin/env python3
"""Generate the paper's measurement tables from the instruments that produce them.

Each table is written to paper/tables/<name>.tex and \\input by paper/main.tex, so a
number in the paper is a file the tools wrote and not a value someone typed. Every
table carries the commit, the machine and the tool it came from; regenerating on a
different machine rewrites those lines with it.

Run:  python3 tools/dev/paper_tables.py [--gpu] [--build-dir build_linux]

--gpu adds the device tables, which need a CUDA build and a visible GPU.
"""

import argparse
import os
import platform
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "paper", "tables")


def run(cmd, timeout=1800):
    p = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, timeout=timeout)
    if p.returncode != 0:
        raise SystemExit("FAILED (%d): %s\n%s" % (p.returncode, " ".join(cmd), p.stderr[-2000:]))
    return p.stdout


def commit():
    return run(["git", "rev-parse", "--short", "HEAD"]).strip()


def machine():
    cpu = "unknown"
    try:
        with open("/proc/cpuinfo") as f:
            for line in f:
                if line.startswith("model name"):
                    cpu = line.split(":", 1)[1].strip()
                    break
    except OSError:
        pass
    mem_gb = "?"
    try:
        with open("/proc/meminfo") as f:
            kb = int(f.readline().split()[1])
            mem_gb = "%.0f" % (kb / 1048576.0)
    except (OSError, ValueError, IndexError):
        pass
    return "%s, %s GB RAM, %s %s" % (cpu, mem_gb, platform.system(), platform.release())


def provenance(tool):
    return ("%% GENERATED by tools/dev/paper_tables.py -- do not edit.\n"
            "%% commit %s | %s | source: %s\n" % (commit(), machine(), tool))


def tex_escape(s):
    return s.replace("_", r"\_").replace("&", r"\&").replace("%", r"\%")


# A TABLE THAT DOES NOT FIT THE TEXT BLOCK IS SHRUNK, AND ONLY THEN.
#
# These tables are generated from measurements, so their width is decided by the data: a run
# that produces longer case names or larger numbers silently pushes the tabular past the margin,
# and LaTeX reports that as an "Overfull \hbox" warning it is very easy to not read. Five of
# these tables were overflowing, the worst by 248pt -- about 8.7cm of table hanging off the page.
#
# \resizebox with the \ifdim guard scales ONLY when the natural width exceeds the line, and
# leaves a table that already fits completely untouched, so nothing that currently typesets
# correctly changes shape. Wrapping at the single point every table is written means a future
# measurement cannot reintroduce the problem in one table and not another.
def _fit(inner):
    """Wrap a tabular so it shrinks to the line width only when it would otherwise overflow."""
    return ("\\resizebox{\\ifdim\\width>\\linewidth\\linewidth\\else\\width\\fi}{!}{%\n"
            + inner + "\n}\n")


def write(name, body):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, name)
    # The provenance comment lines stay OUTSIDE the box: they are comments, and a \resizebox
    # argument must be typesettable material.
    head = [ln for ln in body.splitlines() if ln.startswith("%")]
    rest = [ln for ln in body.splitlines() if not ln.startswith("%")]
    boxed = "\n".join(head) + "\n" + _fit("\n".join(rest).strip())
    with open(path, "w") as f:
        f.write(boxed)
    print("wrote %s" % os.path.relpath(path, ROOT))


# --- T1: exactness and deterministic memory, one row per corpus workload ------------

def t1(build):
    out = run([os.path.join(build, "cost_matrix")])
    rows = []
    total = ""
    for line in out.splitlines():
        m = re.match(r"^(\S+)\s+(\S+)\s+(EXACT|INEXACT|\S+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+"
                     r"(\d+)\s+(\d+)\s+(\d+)\s+(\d+)", line)
        if m:
            rows.append(m.groups())
        elif line.startswith("arena bytes, all artifacts"):
            total = line.strip()
    if not rows:
        raise SystemExit("cost_matrix produced no parseable rows")

    b = [provenance("tools/cost_matrix.cpp"),
         r"\begin{tabular}{llrrrrrrrl}", r"\toprule",
         r"Workload & Class & Canon.\ states & Events & Causal & Branchial & "
         r"Arena B & Heap B & Heap allocs & Exactness \\", r"\midrule"]
    for (case, cls, exact, canon, ev, ca, br, arena, heapb, heapa, _norel) in rows:
        b.append("%s & %s & %s & %s & %s & %s & %s & %s & %s & \\textsc{%s} \\\\" % (
            tex_escape(case), tex_escape(cls), canon, ev, ca, br, arena, heapb, heapa,
            exact.lower()))
    b += [r"\bottomrule", r"\end{tabular}", "", "%% " + total]
    write("t1_exactness.tex", "\n".join(b) + "\n")
    return len(rows)


# --- T8: thread scaling, and the single-thread column T2 compares against -----------

def scaling(build, tool, name, steps, iters, caption_tool):
    out = run([os.path.join(build, tool), str(steps), str(iters)], timeout=3600)
    rows = []
    for line in out.splitlines():
        m = re.search(r"threads=(\d+)\s+steps=(\d+)\s+canonical=(\d+)\s+raw=(\d+)\s+"
                      r"median_ms=([\d.]+)\s+min_ms=([\d.]+)", line)
        if m:
            rows.append(m.groups())
    if not rows:
        raise SystemExit("%s produced no parseable rows:\n%s" % (tool, out[-2000:]))
    base = float(rows[0][4])
    b = [provenance(caption_tool),
         r"\begin{tabular}{rrrrrr}", r"\toprule",
         r"Threads & Steps & Canonical states & Raw states & Median ms & Speedup vs.\ 1 thread \\",
         r"\midrule"]
    for (th, st, canon, raw, med, _mn) in rows:
        b.append("%s & %s & %s & %s & %s & %.2f \\\\" % (th, st, canon, raw, med, base / float(med)))
    b += [r"\bottomrule", r"\end{tabular}"]
    write(name, "\n".join(b) + "\n")
    return len(rows)


def t7(build, gpu_build, steps_list, iters):
    """GPU against CPU on ONE workload, at increasing depth.

    bench_cpu_evolve and bench_gpu_evolve run the same WPP rule, the same two-edge initial
    condition, Full canonicalization and quotient exploration, so the medians are comparable.
    Both are medians of the same iteration count taken in the same session, because wall clock
    on this class of machine drifts more between sessions than the effects being reported.
    """
    rows = []
    for st in steps_list:
        gout = run([os.path.join(gpu_build, "bench_gpu_evolve"), str(st), str(iters)], timeout=3600)
        m = re.search(r"steps=(\d+) states=(\d+) events=(\d+) \| evolve\(\)_median_ms=([\d.]+) \| "
                      r"PersistentEvolver_median_ms=([\d.]+)", gout)
        if not m:
            raise SystemExit("bench_gpu_evolve produced no parseable row:\n%s" % gout[-2000:])
        _, states, events, gpu_call, gpu_persist = m.groups()

        cout = run([os.path.join(build, "bench_cpu_evolve"), str(st), str(iters)], timeout=3600)
        cpu = {}
        for line in cout.splitlines():
            c = re.search(r"threads=(\d+)\s+steps=\d+\s+canonical=\d+\s+raw=(\d+)\s+median_ms=([\d.]+)", line)
            if c:
                cpu[int(c.group(1))] = float(c.group(3))
        if 1 not in cpu or 8 not in cpu:
            raise SystemExit("bench_cpu_evolve gave no 1- and 8-thread rows:\n%s" % cout[-2000:])
        rows.append((st, states, events, cpu[1], cpu[8], float(gpu_persist), float(gpu_call)))

    b = [provenance("tools/bench_cpu_evolve.cpp + tools/bench_gpu_evolve.cpp"),
         r"\begin{tabular}{rrrrrrrr}", r"\toprule",
         r"Steps & Raw states & Events & CPU 1t ms & CPU 8t ms & GPU ms & vs.\ CPU 1t & vs.\ CPU 8t \\",
         r"\midrule"]
    for (st, states, events, c1, c8, gpu, _call) in rows:
        b.append("%d & %s & %s & %.1f & %.1f & %.1f & %.2f & %.2f \\\\" % (
            st, states, events, c1, c8, gpu, c1 / gpu, c8 / gpu))
    b += [r"\bottomrule", r"\end{tabular}"]
    write("t7_gpu.tex", "\n".join(b) + "\n")
    return len(rows)


def t6(build, maxd):
    """Quotient exploration against full capture, and what exactness costs on top.

    One workload (wolfram-2to4) at increasing depth. The events and causal columns are the
    point: quotient alone reports fewer, quotient plus reconstruction reports the full-capture
    numbers exactly, at the quotient's cost.
    """
    out = run([os.path.join(build, "quotient_reconstruction_cost_probe"), str(maxd)], timeout=3600)
    rows = []
    for line in out.splitlines():
        m = re.match(r"\s*(\d+) \|\s*(\d+)\s+(\d+)\s+(\d+)\s+([\d.]+) \|"
                     r"\s*(\d+)\s+(\d+)\s+(\d+)\s+([\d.]+) \|"
                     r"\s*(\d+)\s+(\d+)\s+(\d+)\s+([\d.]+)\s+(\w+)", line)
        if m:
            rows.append(m.groups())
    if not rows:
        raise SystemExit("quotient probe produced no parseable rows:\n%s" % out[-2000:])
    b = [provenance("tools/quotient_reconstruction_cost_probe.cpp"),
         r"\begin{tabular}{rrrrrrrrl}", r"\toprule",
         r"Depth & Events (full) & Causal (full) & ms (full) & Events (quot.) & ms (quot.) & "
         r"Events (quot.+recon) & ms (quot.+recon) & Exact \\", r"\midrule"]
    for (d, _fst, fev, fca, fms, _qst, qev, _qca, qms, _rst, rev, _rca, rms, exact) in rows:
        b.append("%s & %s & %s & %s & %s & %s & %s & %s & \\textsc{%s} \\\\" % (
            d, fev, fca, fms, qev, qms, rev, rms, exact))
    b += [r"\bottomrule", r"\end{tabular}"]
    write("t6_quotient.tex", "\n".join(b) + "\n")
    return len(rows)


def wolframscript():
    """The kernel driver, native if present, else the Windows install this box runs under WSL."""
    from shutil import which
    exe = os.environ.get("HG_WOLFRAMSCRIPT") or which("wolframscript")
    if exe:
        return [exe], False
    import glob
    cands = sorted(glob.glob("/mnt/c/Program Files/Wolfram*/*/*/wolframscript.exe"))
    if cands:
        return [cands[-1]], True
    return None, False


def t2(build, maxd, reps):
    """The engine against the authority, on one workload, at increasing depth.

    THE COMPARISON BASIS IS THE WHOLE PROBLEM HERE, and getting it wrong inflated an earlier
    version of this table by two orders of magnitude. Wolfram/Multicomputation's MultiwaySystem
    exposes NO property that returns the state set as data -- every one of them is graph-valued
    (StatesGraph, CausalGraph, EvolutionGraph, ...) -- so its time necessarily includes building
    Wolfram Graph objects and no subtraction from outside can remove that. Timing OUR side at the
    C++ API, which does no marshalling and builds no graph, and dividing, compares two different
    quantities.

    So the table reports two rows per depth and takes its ratio from the LIKE-FOR-LIKE pair:

      authority   MultiwaySystem, timed the only way its API allows.
      engine      this engine reached the way a user reaches it -- through the paclet, over the
                  wire to the worker process, building the same kind of Wolfram structures.

    The engine's C++ core time is carried in its own column, clearly labelled, because it answers
    a different question (what the engine costs) and must never be divided into the authority's.
    """
    ws, windows = wolframscript()
    if not ws:
        print("T2 skipped: no wolframscript on this machine")
        return 0
    script = os.path.join(ROOT, "reference", "bench_authority.wls")
    if windows:
        script = subprocess.run(["wslpath", "-w", script], capture_output=True, text=True).stdout.strip()
    out = run(ws + ["-file", script, str(maxd), str(reps)], timeout=7200)
    auth, hgev = {}, {}
    for line in out.splitlines():
        m = re.search(r"AUTH d=(\d+) states=(\d+) causal=(\d+) ms=([\d.]+)", line)
        if m:
            auth[int(m.group(1))] = (int(m.group(2)), int(m.group(3)), float(m.group(4)))
        m = re.search(r"HGEV d=(\d+) states=(\d+) causal=(\d+) ms=([\d.]+)", line)
        if m:
            hgev[int(m.group(1))] = (int(m.group(2)), int(m.group(3)), float(m.group(4)))
    if not auth or not hgev:
        raise SystemExit("bench_authority.wls printed no comparable rows:\n%s" % out[-2000:])

    eng = run([os.path.join(build, "quotient_reconstruction_cost_probe"), str(max(auth))],
              timeout=3600)
    core = {}
    for line in eng.splitlines():
        m = re.match(r"\s*(\d+) \|\s*(\d+)\s+\d+\s+\d+\s+([\d.]+) \|", line)
        if m:
            core[int(m.group(1))] = float(m.group(3))

    b = [provenance("reference/bench_authority.wls + tools/quotient_reconstruction_cost_probe.cpp"),
         r"\begin{tabular}{rrrrrrl}", r"\toprule",
         r"Depth & States & Authority ms & Engine ms (paclet) & Like-for-like & "
         r"Engine ms (C++ core) & Counts agree \\", r"\midrule"]
    for d in sorted(auth):
        if d not in hgev:
            continue
        a_states, a_causal, a_ms = auth[d]
        h_states, h_causal, h_ms = hgev[d]
        agree = "yes" if (a_states, a_causal) == (h_states, h_causal) else "NO"
        c = core.get(d)
        b.append("%d & %d & %.1f & %.1f & %.0f$\\times$ & %s & %s \\\\" % (
            d, a_states, a_ms, h_ms, a_ms / h_ms, ("%.1f" % c) if c else "--", agree))
    b += [r"\bottomrule", r"\end{tabular}"]
    write("t2_speedup.tex", "\n".join(b) + "\n")
    return len(auth)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--build-dir", default="build_linux")
    ap.add_argument("--gpu-build-dir", default="build_gpu")
    ap.add_argument("--gpu", action="store_true")
    ap.add_argument("--steps", type=int, default=6)
    ap.add_argument("--iters", type=int, default=15)
    ap.add_argument("--quotient-depth", type=int, default=7)
    ap.add_argument("--authority-depth", type=int, default=5)
    ap.add_argument("--reps", type=int, default=3)
    ap.add_argument("--wolfram", action="store_true",
                    help="add T2, which needs a Wolfram kernel")
    a = ap.parse_args()

    n = t1(a.build_dir)
    print("T1: %d workloads" % n)
    n = scaling(a.build_dir, "bench_cpu_evolve", "t8_scaling.tex", a.steps, a.iters,
                "tools/bench_cpu_evolve.cpp")
    print("T8: %d thread counts" % n)
    if a.wolfram:
        n = t2(a.build_dir, a.authority_depth, a.reps)
        print("T2: %d depths" % n)
    n = t10(a.build_dir)
    print("T10: %d workloads" % n)
    n = t3(a.build_dir)
    print("T3: %d workloads" % n)
    n = t9(a.build_dir, a.iters)
    print("T9: %d contributions" % n)
    n = t6(a.build_dir, a.quotient_depth)
    print("T6: %d depths" % n)
    if a.gpu:
        n = t7(a.build_dir, a.gpu_build_dir, [5, 6, 7], a.iters)
        print("T7: %d depths" % n)
    return 0


if __name__ == "__main__":
    sys.exit(main())
