#!/usr/bin/env python3
"""Generate the paper's measurement tables from the instruments that produce them.

Each table is written to paper/tables/<name>.tex and \\input by paper/main.tex, so a
number in the paper is a file the tools wrote and not a value someone typed. Every
table carries the commit, the machine and the tool it came from; regenerating on a
different machine rewrites those lines with it.

Run:  python3 tools/dev/paper_tables.py [--gpu] [--build-dir build_linux]

--gpu adds the device tables, which need a CUDA build and a visible GPU.
"""

import argparse
import os
import platform
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "paper", "tables")


def run(cmd, timeout=1800):
    p = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, timeout=timeout)
    if p.returncode != 0:
        raise SystemExit("FAILED (%d): %s\n%s" % (p.returncode, " ".join(cmd), p.stderr[-2000:]))
    return p.stdout


def commit():
    return run(["git", "rev-parse", "--short", "HEAD"]).strip()


def machine():
    cpu = "unknown"
    try:
        with open("/proc/cpuinfo") as f:
            for line in f:
                if line.startswith("model name"):
                    cpu = line.split(":", 1)[1].strip()
                    break
    except OSError:
        pass
    mem_gb = "?"
    try:
        with open("/proc/meminfo") as f:
            kb = int(f.readline().split()[1])
            mem_gb = "%.0f" % (kb / 1048576.0)
    except (OSError, ValueError, IndexError):
        pass
    return "%s, %s GB RAM, %s %s" % (cpu, mem_gb, platform.system(), platform.release())


def provenance(tool):
    return ("%% GENERATED by tools/dev/paper_tables.py -- do not edit.\n"
            "%% commit %s | %s | source: %s\n" % (commit(), machine(), tool))


def tex_escape(s):
    return s.replace("_", r"\_").replace("&", r"\&").replace("%", r"\%")


# A TABLE THAT DOES NOT FIT THE TEXT BLOCK IS SHRUNK, AND ONLY THEN.
#
# These tables are generated from measurements, so their width is decided by the data: a run
# that produces longer case names or larger numbers silently pushes the tabular past the margin,
# and LaTeX reports that as an "Overfull \hbox" warning it is very easy to not read. Five of
# these tables were overflowing, the worst by 248pt -- about 8.7cm of table hanging off the page.
#
# \resizebox with the \ifdim guard scales ONLY when the natural width exceeds the line, and
# leaves a table that already fits completely untouched, so nothing that currently typesets
# correctly changes shape. Wrapping at the single point every table is written means a future
# measurement cannot reintroduce the problem in one table and not another.
def _fit(inner):
    """Wrap a tabular so it shrinks to the line width only when it would otherwise overflow."""
    return ("\\resizebox{\\ifdim\\width>\\linewidth\\linewidth\\else\\width\\fi}{!}{%\n"
            + inner + "\n}\n")


def write_raw(name, body):
    """Emit a fragment verbatim. Figure data is pgfplots commands, not a tabular, so it must not
    be wrapped in the resizebox write() applies."""
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, name)
    with open(path, "w") as f:
        f.write(body)
    print("wrote %s" % os.path.relpath(path, ROOT))


def write(name, body):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, name)
    # The provenance comment lines stay OUTSIDE the box: they are comments, and a \resizebox
    # argument must be typesettable material.
    head = [ln for ln in body.splitlines() if ln.startswith("%")]
    rest = [ln for ln in body.splitlines() if not ln.startswith("%")]
    boxed = "\n".join(head) + "\n" + _fit("\n".join(rest).strip())
    with open(path, "w") as f:
        f.write(boxed)
    print("wrote %s" % os.path.relpath(path, ROOT))


# --- T1: exactness and deterministic memory, one row per corpus workload ------------

def t1(build):
    out = run([os.path.join(build, "cost_matrix")])
    rows = []
    total = ""
    for line in out.splitlines():
        m = re.match(r"^(\S+)\s+(\S+)\s+(EXACT|INEXACT|\S+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+"
                     r"(\d+)\s+(\d+)\s+(\d+)\s+(\d+)", line)
        if m:
            rows.append(m.groups())
        elif line.startswith("arena bytes, all artifacts"):
            total = line.strip()
    if not rows:
        raise SystemExit("cost_matrix produced no parseable rows")

    b = [provenance("tools/cost_matrix.cpp"),
         r"\begin{tabular}{llrrrrrrrl}", r"\toprule",
         r"Workload & Class & Canon.\ states & Events & Causal & Branchial & "
         r"Arena B & Heap B & Heap allocs & Exactness \\", r"\midrule"]
    # cost_matrix's first numeric column is `raw` -- the raw state count, ahead of `canon`. Every
    # column here is named against that header, so the unpacking names it and drops it rather
    # than letting the values slide one place to the left.
    for (case, cls, exact, _raw, canon, ev, ca, br, arena, heapb, heapa) in rows:
        b.append("%s & %s & %s & %s & %s & %s & %s & %s & %s & %s \\\\" % (
            tex_escape(case), tex_escape(cls), canon, ev, ca, br, arena, heapb, heapa,
            exact.lower()))
    b += [r"\bottomrule", r"\end{tabular}", "", "%% " + total]
    write("t1_exactness.tex", "\n".join(b) + "\n")
    return len(rows)


def cr_ratio(build, low_steps):
    """C/R per corpus case at two depths, for Proposition 1's ceiling.

    C/R is cost_matrix's `wlceil` column: the fraction of IR invocations a Weisfeiler--Leman
    pre-filter could elide, which the proposition bounds above by the ratio of canonical classes
    to raw states. Two runs, because the claim is that the ratio FALLS with depth, and one depth
    cannot show a direction. The lower sample is taken with an explicit step override; the higher
    is each case's own measure_steps, which is what every other table here reports.

    The eight cases are named rather than taken from the whole corpus: the figure plots one bar
    pair each and the surrounding text refers to them individually.
    """
    row_re = (r"^(\S+)\s+(\S+)\s+(?:EXACT|INEXACT|\S+)\s+\d+\s+\d+\s+(\d+)"
              r"\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+\d+\s+[\d.]+\s+([\d.]+)%")

    def sample(args):
        out = run([os.path.join(build, "cost_matrix")] + args, timeout=1800)
        got = {}
        for line in out.splitlines():
            m = re.match(row_re, line)
            if m:
                got[m.group(1)] = (m.group(2), int(m.group(3)), float(m.group(4)))
        if not got:
            raise SystemExit("cost_matrix produced no parseable C/R rows:\n%s" % out[-1500:])
        return got

    high = sample([])
    low = sample([str(low_steps)])

    # (case in cost_matrix, short name on the figure's x axis)
    cases = [("cycle4-automorphic", "cycle4"), ("star4-automorphic", "star4"),
             ("disconnected-lhs", "disconn"), ("binary-growth", "binary"),
             ("multi-rule", "multi"), ("triangle", "triangle"),
             ("arity3-growth", "arity3"), ("self-loop", "self-loop")]
    rows = [(c, s, high[c], low.get(c)) for (c, s) in cases if c in high]
    rows.sort(key=lambda r: r[2][2])

    b = [provenance("tools/cost_matrix.cpp"),
         r"\begin{tabular}{llrrr}", r"\toprule",
         r"Case & Rule type & Events & $C/R$ & $C/R$ at lower depth \\", r"\midrule"]
    for (case, _short, h, l) in rows:
        b.append("\\texttt{%s} & %s & %s & %s\\%% & %s \\\\" % (
            tex_escape(case), tex_escape(h[0]), "{:,}".format(h[1]).replace(",", "{,}"),
            ("%g" % h[2]), ("%g\\%%" % l[2]) if l else "--"))
    b += [r"\bottomrule", r"\end{tabular}"]
    write("t_crratio.tex", "\n".join(b) + "\n")

    coords = lambda idx: "".join("(%s,%g)" % (r[1], r[idx][2]) for r in rows if r[idx])
    # The x axis is symbolic and its coordinate list must be declared before the axis begins,
    # while the plots go inside it. Two fragments, because one file cannot be input in both
    # places, and the order of the names has to match the order of the bars.
    syms = ",".join(r[1] for r in rows)
    write_raw("f_crratio_syms.tex",
              provenance("tools/cost_matrix.cpp") + "\n"
              + r"\pgfplotsset{crsymbolic/.style={symbolic x coords={%s}}}" % syms + "\n")
    f = [provenance("tools/cost_matrix.cpp"),
         r"\addplot[fill=gray!55, draw=black] coordinates {%s};" % coords(3),
         r"\addlegendentry{lower depth}",
         r"\addplot[fill=white, draw=black] coordinates {%s};" % coords(2),
         r"\addlegendentry{higher depth}"]
    write_raw("f_crratio.tex", "\n".join(f) + "\n")
    return len(rows)


# --- T8: thread scaling, and the single-thread column T2 compares against -----------

def scaling(build, tool, name, steps, iters, caption_tool):
    out = run([os.path.join(build, tool), str(steps), str(iters)], timeout=3600)
    rows = []
    for line in out.splitlines():
        m = re.search(r"threads=(\d+)\s+steps=(\d+)\s+canonical=(\d+)\s+raw=(\d+)\s+"
                      r"median_ms=([\d.]+)\s+min_ms=([\d.]+)", line)
        if m:
            rows.append(m.groups())
    if not rows:
        raise SystemExit("%s produced no parseable rows:\n%s" % (tool, out[-2000:]))
    base = float(rows[0][4])
    b = [provenance(caption_tool),
         r"\begin{tabular}{rrrrrr}", r"\toprule",
         r"Threads & Steps & Canonical states & Raw states & Median ms & Speedup vs.\ 1 thread \\",
         r"\midrule"]
    for (th, st, canon, raw, med, _mn) in rows:
        b.append("%s & %s & %s & %s & %s & %.2f \\\\" % (th, st, canon, raw, med, base / float(med)))
    b += [r"\bottomrule", r"\end{tabular}"]
    write(name, "\n".join(b) + "\n")

    # The conclusion states the best speedup and the thread count it occurs at. Emitting them as
    # macros is what keeps that sentence from drifting when this table is regenerated: the prose
    # cites the value rather than repeating it.
    best_t, best_s = max(((int(r[0]), base / float(r[4])) for r in rows), key=lambda p: p[1])
    write_raw("values.tex",
              provenance(caption_tool) + "\n"
              + r"\newcommand{\MaxHostSpeedup}{%.1f}" % best_s + "\n"
              + r"\newcommand{\MaxHostSpeedupThreads}{%d}" % best_t + "\n")
    return len(rows)


def t7(build, gpu_build, steps_list, iters):
    """GPU against CPU on ONE workload, at increasing depth.

    bench_cpu_evolve and bench_gpu_evolve run the same WPP rule, the same two-edge initial
    condition, Full canonicalization and quotient exploration, so the medians are comparable.
    Both are medians of the same iteration count taken in the same session, because wall clock
    on this class of machine drifts more between sessions than the effects being reported.
    """
    rows = []
    for st in steps_list:
        gout = run([os.path.join(gpu_build, "bench_gpu_evolve"), str(st), str(iters)], timeout=3600)
        m = re.search(r"steps=(\d+) states=(\d+) events=(\d+) \| evolve\(\)_median_ms=([\d.]+) \| "
                      r"PersistentEvolver_median_ms=([\d.]+)", gout)
        if not m:
            raise SystemExit("bench_gpu_evolve produced no parseable row:\n%s" % gout[-2000:])
        _, states, events, gpu_call, gpu_persist = m.groups()

        cout = run([os.path.join(build, "bench_cpu_evolve"), str(st), str(iters)], timeout=3600)
        cpu = {}
        for line in cout.splitlines():
            c = re.search(r"threads=(\d+)\s+steps=\d+\s+canonical=\d+\s+raw=(\d+)\s+median_ms=([\d.]+)", line)
            if c:
                cpu[int(c.group(1))] = float(c.group(3))
        if 1 not in cpu or 8 not in cpu:
            raise SystemExit("bench_cpu_evolve gave no 1- and 8-thread rows:\n%s" % cout[-2000:])
        rows.append((st, states, events, cpu[1], cpu[8], float(gpu_persist), float(gpu_call)))

    b = [provenance("tools/bench_cpu_evolve.cpp + tools/bench_gpu_evolve.cpp"),
         r"\begin{tabular}{rrrrrrrr}", r"\toprule",
         r"Steps & Raw states & Events & CPU 1t ms & CPU 8t ms & GPU ms & vs.\ CPU 1t & vs.\ CPU 8t \\",
         r"\midrule"]
    for (st, states, events, c1, c8, gpu, _call) in rows:
        b.append("%d & %s & %s & %.1f & %.1f & %.1f & %.2f & %.2f \\\\" % (
            st, states, events, c1, c8, gpu, c1 / gpu, c8 / gpu))
    b += [r"\bottomrule", r"\end{tabular}"]
    write("t7_gpu.tex", "\n".join(b) + "\n")

    # The left panel of the GPU figure plots the CPU 8-thread and GPU columns of this table.
    cpu_pts = "".join("(%d,%.1f)" % (r[0], r[4]) for r in rows)
    gpu_pts = "".join("(%d,%.1f)" % (r[0], r[5]) for r in rows)
    f = [provenance("tools/bench_cpu_evolve.cpp + tools/bench_gpu_evolve.cpp"),
         r"\addplot[mark=*, black] coordinates {%s};" % cpu_pts,
         r"\addlegendentry{CPU, 8 threads}",
         r"\addplot[mark=square, black, dashed] coordinates {%s};" % gpu_pts,
         r"\addlegendentry{GPU}"]
    write_raw("f_gpu_depth.tex", "\n".join(f) + "\n")
    return len(rows)


def t6(build, maxd):
    """Quotient exploration against full capture, and what exactness costs on top.

    One workload (wolfram-2to4) at increasing depth. The events and causal columns are the
    point: quotient alone reports fewer, quotient plus reconstruction reports the full-capture
    numbers exactly, at the quotient's cost.
    """
    out = run([os.path.join(build, "quotient_reconstruction_cost_probe"), str(maxd)], timeout=3600)
    rows = []
    for line in out.splitlines():
        m = re.match(r"\s*(\d+) \|\s*(\d+)\s+(\d+)\s+(\d+)\s+([\d.]+) \|"
                     r"\s*(\d+)\s+(\d+)\s+(\d+)\s+([\d.]+) \|"
                     r"\s*(\d+)\s+(\d+)\s+(\d+)\s+([\d.]+)\s+(\w+)", line)
        if m:
            rows.append(m.groups())
    if not rows:
        raise SystemExit("quotient probe produced no parseable rows:\n%s" % out[-2000:])
    b = [provenance("tools/quotient_reconstruction_cost_probe.cpp"),
         r"\begin{tabular}{rrrrrrrrl}", r"\toprule",
         r"Depth & Events (full) & Causal (full) & ms (full) & Events (quot.) & ms (quot.) & "
         r"Events (quot.+recon) & ms (quot.+recon) & Exact \\", r"\midrule"]
    for (d, _fst, fev, fca, fms, _qst, qev, _qca, qms, _rst, rev, _rca, rms, exact) in rows:
        b.append("%s & %s & %s & %s & %s & %s & %s & %s & %s \\\\" % (
            d, fev, fca, fms, qev, qms, rev, rms, exact))
    b += [r"\bottomrule", r"\end{tabular}"]
    write("t6_quotient.tex", "\n".join(b) + "\n")
    return len(rows)


def wolframscript():
    """The kernel driver, native if present, else the Windows install this box runs under WSL."""
    from shutil import which
    exe = os.environ.get("HG_WOLFRAMSCRIPT") or which("wolframscript")
    if exe:
        return [exe], False
    import glob
    cands = sorted(glob.glob("/mnt/c/Program Files/Wolfram*/*/*/wolframscript.exe"))
    if cands:
        return [cands[-1]], True
    return None, False


def t2(build, maxd, reps):
    """The engine against the authority, on one workload, at increasing depth.

    THE COMPARISON BASIS IS THE WHOLE PROBLEM HERE, and getting it wrong inflated an earlier
    version of this table by two orders of magnitude. Wolfram/Multicomputation's MultiwaySystem
    exposes NO property that returns the state set as data -- every one of them is graph-valued
    (StatesGraph, CausalGraph, EvolutionGraph, ...) -- so its time necessarily includes building
    Wolfram Graph objects and no subtraction from outside can remove that. Timing OUR side at the
    C++ API, which does no marshalling and builds no graph, and dividing, compares two different
    quantities.

    So the table reports two rows per depth and takes its ratio from the LIKE-FOR-LIKE pair:

      authority   MultiwaySystem, timed the only way its API allows.
      engine      this engine reached the way a user reaches it -- through the paclet, over the
                  wire to the worker process, building the same kind of Wolfram structures.

    The engine's C++ core time is carried in its own column, clearly labelled, because it answers
    a different question (what the engine costs) and must never be divided into the authority's.
    """
    ws, windows = wolframscript()
    if not ws:
        print("T2 skipped: no wolframscript on this machine")
        return 0
    script = os.path.join(ROOT, "reference", "bench_authority.wls")
    if windows:
        script = subprocess.run(["wslpath", "-w", script], capture_output=True, text=True).stdout.strip()
    out = run(ws + ["-file", script, str(maxd), str(reps)], timeout=7200)
    auth, hgev, ref = {}, {}, {}
    for line in out.splitlines():
        m = re.search(r"AUTH d=(\d+) states=(\d+) causal=(\d+) ms=([\d.]+)", line)
        if m:
            auth[int(m.group(1))] = (int(m.group(2)), int(m.group(3)), float(m.group(4)))
        m = re.search(r"HGEV d=(\d+) states=(\d+) causal=(\d+) ms=([\d.]+)", line)
        if m:
            hgev[int(m.group(1))] = (int(m.group(2)), int(m.group(3)), float(m.group(4)))
        # OUR OWN reference implementation, the second thing the engine is compared with.
        m = re.search(r"REF\s+d=(\d+) states=(\d+) causal=(\d+) ms=([\d.]+)", line)
        if m:
            ref[int(m.group(1))] = (int(m.group(2)), int(m.group(3)), float(m.group(4)))
    if not auth or not hgev:
        raise SystemExit("bench_authority.wls printed no comparable rows:\n%s" % out[-2000:])

    eng = run([os.path.join(build, "quotient_reconstruction_cost_probe"), str(max(auth))],
              timeout=3600)
    core = {}
    for line in eng.splitlines():
        m = re.match(r"\s*(\d+) \|\s*(\d+)\s+\d+\s+\d+\s+([\d.]+) \|", line)
        if m:
            core[int(m.group(1))] = float(m.group(3))

    b = [provenance("reference/bench_authority.wls + tools/quotient_reconstruction_cost_probe.cpp"),
         r"\begin{tabular}{rrrrrrrrl}", r"\toprule",
         r"Depth & States & Authority ms & Reference ms & Engine ms (paclet) & "
         r"Engine ms (C++ core) & Speedup vs authority & Speedup vs reference & "
         r"Counts agree \\", r"\midrule"]
    for d in sorted(auth):
        if d not in hgev:
            continue
        a_states, a_causal, a_ms = auth[d]
        h_states, h_causal, h_ms = hgev[d]
        r_states, r_causal, r_ms = ref.get(d, (None, None, None))
        # Every implementation in the row must have computed the same thing, or the times are
        # not comparable. The reference is included in that test, not exempt from it.
        same = (a_states, a_causal) == (h_states, h_causal)
        if r_ms is not None:
            same = same and (r_states, r_causal) == (a_states, a_causal)
        agree = "yes" if same else "NO"
        c = core.get(d)
        # The engine's C++ core against the reference: both compute DATA, so neither is charged
        # for building Wolfram Graph objects and the ratio is not a graph-construction artefact.
        vs_ref = ("%.0f$\\times$" % (r_ms / c)) if (r_ms is not None and c) else "--"
        # The engine's C++ core against the authority. Both sides are stated in the row beside
        # it -- the authority's time includes building Wolfram Graph objects, because its
        # MultiwaySystem exposes no property returning the state set as data, while the core
        # builds none. That asymmetry is the reason the paclet column sits here too: it is the
        # same-basis comparison, and this column is the engine's own speed with nothing
        # marshalled.
        vs_auth = ("%.0f$\\times$" % (a_ms / c)) if c else "--"
        b.append("%d & %d & %.1f & %s & %.1f & %s & %s & %s & %s \\\\" % (
            d, a_states, a_ms, ("%.1f" % r_ms) if r_ms is not None else "--", h_ms,
            ("%.1f" % c) if c else "--", vs_auth, vs_ref, agree))
    b += [r"\bottomrule", r"\end{tabular}"]
    write("t2_speedup.tex", "\n".join(b) + "\n")

    # The figure beside this table plots the same two series. Emitting them here is what keeps
    # the figure and the table from drifting: one run produces both, so a regenerated table
    # cannot leave the plot showing the previous run's numbers.
    depths = [d for d in sorted(auth) if d in hgev and core.get(d)]
    auth_pts = "".join("(%d,%.1f)" % (d, auth[d][2]) for d in depths)
    core_pts = "".join("(%d,%.1f)" % (d, core[d]) for d in depths)
    f = [provenance("reference/bench_authority.wls + tools/quotient_reconstruction_cost_probe.cpp"),
         r"\addplot[mark=square*, black, dashed] coordinates {%s};" % auth_pts,
         r"\addlegendentry{\texttt{Wolfram/\allowbreak Multicomputation}}",
         r"\addplot[mark=*, black] coordinates {%s};" % core_pts,
         r"\addlegendentry{this engine}"]
    write_raw("f_speedup.tex", "\n".join(f) + "\n")
    return len(auth)


def t9(build, iters):
    """Per-contribution ablation, from the switches the shipped binary still has.

    There are no compiled-out ablation builds to run: when a replacement lands here the
    replaced path is deleted in the same commit, so an "off" arm exists only where the choice
    is still a live switch. Those are match forwarding (which the rule set decides) and the
    state-canonicalization mode. Each row is a median over the same iteration count, and the
    state and event counts are printed so a row that changed the ANSWER is visible rather than
    read as a speedup.
    """
    def smoke(arm, rule, edges, steps, canon):
        best = None
        for _ in range(max(3, iters // 3)):
            out = run([os.path.join(build, "sampling_cost_smoke"), arm, rule, str(edges),
                       str(steps), "4", "4", canon], timeout=1800)
            m = re.search(r"done ([\d.]+) ms\s+states=(\d+).*events=(\d+)", out)
            if not m:
                raise SystemExit("sampling_cost_smoke gave no row:\n%s" % out[-1000:])
            ms, st, ev = float(m.group(1)), m.group(2), m.group(3)
            if best is None or ms < best[0]:
                best = (ms, st, ev)
        return best

    rows = []
    a = smoke("off", "growth", 1, 8, "full")       # forwarding decided: off on a one-edge LHS
    b = smoke("fwdon", "growth", 1, 8, "full")     # forced on
    rows.append(("Match forwarding, one-edge LHS", "on", b, "decided off", a))
    a = smoke("off", "pair", 4, 6, "full")         # forwarding decided: on for a two-edge LHS
    b = smoke("fwdoff", "pair", 4, 6, "full")      # forced off
    rows.append(("Match forwarding, two-edge LHS", "off", b, "decided on", a))
    a = smoke("off", "pair", 4, 6, "automatic")
    b = smoke("off", "pair", 4, 6, "full")
    rows.append(("State canonicalization", "Full (exact)", b, "Automatic (hash)", a))

    b_ = [provenance("tools/sampling_cost_smoke.cpp"),
          r"\begin{tabular}{lllrlrl}", r"\toprule",
          r"Contribution & Arm A & A ms & Arm B & B ms & Ratio & Same answer \\", r"\midrule"]
    for (name, an, av, bn, bv) in rows:
        same = "yes" if (av[1], av[2]) == (bv[1], bv[2]) else "NO"
        b_.append("%s & %s & %.1f & %s & %.1f & %.2f & %s \\\\" % (
            name, an, av[0], bn, bv[0], av[0] / bv[0], same))
    b_ += [r"\bottomrule", r"\end{tabular}"]
    write("t9_ablation.tex", "\n".join(b_) + "\n")
    return len(rows)


def t3(build):
    """Is the global allocator on the concurrent path?

    The de-heap, the causal-closure rework and the copy-on-write states were scaffolded in the
    paper as three before/after tables. Their "before" columns are not reproducible as a
    comparison: each replaced path was deleted in the commit that replaced it (there is no build
    flag that restores it), the work spans dozens of commits on one branch, and the instrument
    that measures arena bytes today did not exist at the far end -- so a before/after pair would
    be two different instruments reporting one column.

    What IS checkable, and is the claim those three items were for: allocation count does not
    grow with the work. cost_matrix counts every global operator new during the measured
    evolution, so the table below puts that count next to the size of the run it served.
    """
    out = run([os.path.join(build, "cost_matrix")])
    rows = []
    for line in out.splitlines():
        m = re.match(r"^(\S+)\s+(\S+)\s+(EXACT|INEXACT|\S+)\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s+"
                     r"(\d+)\s+(\d+)\s+(\d+)\s+(\d+)", line)
        if m:
            g = m.groups()
            # Against cost_matrix's header: g[3] is raw, g[4] canon, g[5] events, g[6] causal,
            # g[7] branch, g[8] arenaB, g[9] heapB, g[10] heapAllocs. This table wants the
            # ALLOCATION count beside the size of the run, so it takes g[10] and not the byte
            # totals either side of it.
            rows.append((g[0], int(g[4]), int(g[5]), int(g[8]), int(g[10])))
    if not rows:
        raise SystemExit("cost_matrix produced no parseable rows")
    rows.sort(key=lambda r: r[2])   # by events: the work, which is what allocation must not track

    b = [provenance("tools/cost_matrix.cpp"),
         r"\begin{tabular}{lrrrrr}", r"\toprule",
         r"Workload & Canon.\ states & Events & Arena B & Heap allocs & Allocs per event \\",
         r"\midrule"]
    for (name, canon, ev, arena, allocs) in rows:
        per = ("%.4f" % (float(allocs) / ev)) if ev else "--"
        b.append("%s & %d & %d & %d & %d & %s \\\\" % (
            tex_escape(name), canon, ev, arena, allocs, per))
    b += [r"\bottomrule", r"\end{tabular}"]
    write("t3_heap.tex", "\n".join(b) + "\n")
    return len(rows)


def t10(build):
    """What each event-identity convention identifies, on the same runs.

    The three conventions are refinements of one another: ByEndpointStates calls two rewrites the
    same event when they run between the same states, ByConsumedProducedEdges when they also move
    the same edges, DistinctApplications never. Reading the CANONICAL EVENT COUNT across them on
    a fixed workload is what shows they are distinct points rather than one convention wearing
    three names -- which inspection cannot show, because a duplicated convention still equals
    itself.

    The counts are taken under Full state canonicalization, one thread. No timing column: the
    conventions differ in what they IDENTIFY, and the cost of the identity is the added IR pass,
    which T9's canonicalization row already measures.
    """
    out = run([os.path.join(build, "mode_matrix_probe")], timeout=1800)
    rows = []
    workload = None
    for line in out.splitlines():
        m = re.match(r"^(\S+) \(steps=(\d+)\)", line)
        if m:
            workload, steps = m.group(1), m.group(2)
            continue
        m = re.match(r"^\s+Full\s+(\d+)/(\d+)/(\d+)/(\d+)\s+(\d+)/(\d+)/(\d+)/(\d+)\s+(\d+)/(\d+)/(\d+)/(\d+)", line)
        if m and workload:
            g = [int(x) for x in m.groups()]
            rows.append((workload, steps, g[0], g[1], g[5], g[9]))
            workload = None
    if not rows:
        raise SystemExit("mode_matrix_probe produced no parseable Full rows:\n%s" % out[-2000:])

    b = [provenance("tools/mode_matrix_probe.cpp"),
         r"\begin{tabular}{lrrrrr}", r"\toprule",
         r"Workload & Steps & Canon.\ states & By endpoint states & By consumed/produced edges & "
         r"Distinct applications \\", r"\midrule"]
    for (name, steps, canon, e1, e2, e3) in rows:
        b.append("%s & %s & %d & %d & %d & %d \\\\" % (tex_escape(name), steps, canon, e1, e2, e3))
    b += [r"\bottomrule", r"\end{tabular}"]
    write("t10_event_canon.tex", "\n".join(b) + "\n")
    return len(rows)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--build-dir", default="build_linux")
    ap.add_argument("--gpu-build-dir", default="build_gpu")
    ap.add_argument("--gpu", action="store_true")
    ap.add_argument("--steps", type=int, default=6)
    ap.add_argument("--iters", type=int, default=15)
    ap.add_argument("--quotient-depth", type=int, default=7)
    ap.add_argument("--authority-depth", type=int, default=5)
    ap.add_argument("--reps", type=int, default=3)
    ap.add_argument("--cr-low-steps", type=int, default=2,
                    help="step override for the lower C/R depth sample")
    ap.add_argument("--wolfram", action="store_true",
                    help="add T2, which needs a Wolfram kernel")
    a = ap.parse_args()

    n = t1(a.build_dir)
    print("T1: %d workloads" % n)
    n = cr_ratio(a.build_dir, a.cr_low_steps)
    print("C/R: %d cases" % n)
    n = scaling(a.build_dir, "bench_cpu_evolve", "t8_scaling.tex", a.steps, a.iters,
                "tools/bench_cpu_evolve.cpp")
    print("T8: %d thread counts" % n)
    if a.wolfram:
        n = t2(a.build_dir, a.authority_depth, a.reps)
        print("T2: %d depths" % n)
    n = t10(a.build_dir)
    print("T10: %d workloads" % n)
    n = t3(a.build_dir)
    print("T3: %d workloads" % n)
    n = t9(a.build_dir, a.iters)
    print("T9: %d contributions" % n)
    n = t6(a.build_dir, a.quotient_depth)
    print("T6: %d depths" % n)
    if a.gpu:
        n = t7(a.build_dir, a.gpu_build_dir, [5, 6, 7], a.iters)
        print("T7: %d depths" % n)
    return 0


if __name__ == "__main__":
    sys.exit(main())
