// generate_golden_matrix.cpp — build reference/golden_matrix.txt, the cached expectations the
// fast gate compares against.
//
// Run deliberately, not on every build: it does the expensive independent checking so the gate
// does not have to. Regenerating is a decision, and reviewing the diff is where a semantic
// change gets noticed rather than silently absorbed.
//
// Every row records what it was checked against, because a golden produced by the engine and
// then compared to the engine proves stability and not correctness. Where the independent
// brute force can reach, the row is an ORACLE row and the generator refuses to emit it unless
// the engine agrees. Where it cannot, the row is a PIN and says so, which is how a cell with
// no independent check stays visible instead of blending in.
//
// Build:
//   g++ -O2 -std=c++20 -pthread -I hypergraph/include -I job_system/include \
//       -I lockfree_deque/include -I common/include -I . \
//       tools/generate_golden_matrix.cpp hypergraph/src/*.cpp -o /tmp/gen_golden
//   /tmp/gen_golden > reference/golden_matrix.txt

#include "reference/golden_matrix.hpp"
#include "reference/oracle_corpus.hpp"

#include <cstdio>
#include <set>
#include <string>
#include <vector>

using namespace hypergraph;
using golden::Provenance;

namespace {

struct Measured {
    uint64_t states, events, causal, pairs, branchial, fingerprint;
};

Measured run(const oracle::Case& c, StateCanonicalizationMode sm, EventSignatureKeys ek,
             bool quotient, int steps, unsigned threads) {
    Hypergraph hg;
    hg.set_state_canonicalization_mode(sm);
    hg.set_event_signature_keys(ek);
    ParallelEvolutionEngine e(&hg, threads);
    e.set_explore_from_canonical_states_only(quotient);
    for (const auto& r : c.rules) e.add_rule(r);
    e.evolve(c.init, steps);

    Measured m{};
    m.states    = hg.num_canonical_states();
    m.events    = hg.observable_num_events();
    m.causal    = hg.observable_num_causal_edges();
    m.pairs     = hg.observable_num_causal_pairs(
        hg.causal_graph().transitive_reduction_enabled());
    m.branchial = hg.observable_num_branchial();
    // Fold each DISTINCT canonical hash once. Folding per raw state weights each class by its
    // member count, which differs between full capture and quotient while the state SET -- the
    // observable -- is identical; the twin check then fails on a multiplicity artifact.
    std::set<uint64_t> canon;
    for (uint32_t sid = 0; sid < hg.num_states(); ++sid) {
        if (hg.get_state(sid).id == INVALID_ID) continue;
        canon.insert(hg.get_or_compute_canonical_hash(sid));
    }
    for (uint64_t h : canon) m.fingerprint = golden::fold_fingerprint(m.fingerprint, h);
    return m;
}

// What an independent map says this cell's state count must be, or "no opinion".
//
// The three state modes are a refinement lattice over the same raw exploration, so quotienting
// the None-mode state set by an independent map gives each mode's expected count: the identity
// for None, content-equality for Automatic, isomorphism for Full. That is what gives the
// non-Full cells an oracle -- the isomorphism count alone answers only for Full, because
// isomorphism is what Full means.
//
// The isomorphism map has a vertex bound; the content map does not, so a workload too large for
// the former can still be checked in None and Automatic.
struct Expectation { bool applicable; size_t states; };

Expectation independent_expectation(const oracle::LatticeCounts& lc,
                                    StateCanonicalizationMode sm, bool quotient) {
    // Quotient expands one representative per class rather than every raw state; the count it
    // reports is the class count, but which states EXIST differs, so the lattice argument above
    // does not transfer and this abstains rather than guessing.
    if (quotient) return {false, 0};
    switch (sm) {
        case StateCanonicalizationMode::None:      return {true, lc.raw};
        case StateCanonicalizationMode::Automatic: return {true, lc.by_content};
        case StateCanonicalizationMode::Full:      return {lc.all_small, lc.by_iso};
    }
    return {false, 0};
}

}  // namespace

int main() {
    const StateCanonicalizationMode state_modes[] = {
        StateCanonicalizationMode::None,
        StateCanonicalizationMode::Automatic,
        StateCanonicalizationMode::Full,
    };
    const EventSignatureKeys event_modes[] = {
        EVENT_SIG_NONE, EVENT_SIG_AUTOMATIC, EVENT_SIG_FULL,
    };

    std::printf("# reference/golden_matrix.txt -- generated by tools/generate_golden_matrix.cpp\n");
    std::printf("# Regenerate deliberately and review the diff: a change here is a change in\n");
    std::printf("# what the engine considers the same state or the same event.\n");
    std::printf("#\n");
    std::printf("# case state_mode event_mode quotient steps states events causal pairs "
                "branchial fingerprint provenance\n");

    size_t oracle_rows = 0, pin_rows = 0, unreachable = 0;

    for (const auto& c : oracle::corpus()) {
        // One raw exploration per workload, quotiented three ways. The brute force is the
        // expensive part, so it runs once per case rather than once per cell.
        const oracle::LatticeCounts lattice =
            oracle::brute_force_lattice(c.rules, c.init, c.oracle_steps);

        for (StateCanonicalizationMode sm : state_modes) {
            for (EventSignatureKeys ek : event_modes) {
                for (bool quotient : {false, true}) {
                    // Quotient exploration requires isomorphism-invariant state identity: it
                    // expands one representative per class, and None/Automatic do not have
                    // classes to take a representative of.
                    if (quotient && sm != StateCanonicalizationMode::Full) continue;

                    const int steps = c.oracle_steps;
                    const Measured m = run(c, sm, ek, quotient, steps, /*threads=*/4);

                    Provenance p = Provenance::Pin;
                    const Expectation exp = independent_expectation(lattice, sm, quotient);
                    if (exp.applicable) {
                        if (exp.states != m.states) {
                            std::fprintf(stderr,
                                "REFUSING: %s %s/%s%s -- engine says %llu states, the "
                                "independent map says %zu. One of them is wrong and neither "
                                "may be cached as an expectation.\n",
                                c.name, golden::state_mode_name(sm),
                                golden::event_keys_name(ek), quotient ? "/quotient" : "",
                                (unsigned long long)m.states, exp.states);
                            return 1;
                        }
                        p = Provenance::Oracle;
                        ++oracle_rows;
                    } else {
                        ++pin_rows;
                        if (!quotient) ++unreachable;
                    }

                    std::printf("%s %s %s %d %d %llu %llu %llu %llu %llu %llu %s\n",
                                c.name,
                                golden::state_mode_name(sm),
                                golden::event_keys_name(ek),
                                quotient ? 1 : 0,
                                steps,
                                (unsigned long long)m.states,
                                (unsigned long long)m.events,
                                (unsigned long long)m.causal,
                                (unsigned long long)m.pairs,
                                (unsigned long long)m.branchial,
                                (unsigned long long)m.fingerprint,
                                golden::provenance_name(p));
                }
            }
        }
    }

    std::fprintf(stderr,
        "rows: %zu independently checked against the brute force, %zu pinned "
        "(%zu of those because the brute force could not reach the workload).\n"
        "A pinned row is a regression tripwire, not a correctness check.\n",
        oracle_rows, pin_rows, unreachable);
    return 0;
}
